
language: ruby
dist: trusty
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
sudo: required
install:
  - sudo apt-get install cmake -y
  - bundle install
before_script:
  - sudo mv etc/config.yaml.travis etc/config.yaml
# TODO: This should be switch to `rake spec:all` once the command specs
# are working again
script: rake spec:unit
