
language: ruby
dist: trusty
rvm:
 - 2.4.1
sudo: required
install:
  - sudo apt-get install cmake -y
  - bundle install
# TODO: This should be switch to `rake spec:all` once the command specs
# are working again
script: rake spec:unit
