
# Config file for false positives to ignore (or other things don't care about)
# when running https://github.com/joshuaclayton/unused.

- name: Ruby
  autoLowLikelihood:

    # Ignore all dependency functions.
    - name: dependency functions
      pathStartsWith: scripts/dependencies

    # Ignore patches for Gems; will often monkey-patch methods to be called by
    # Gem code which would otherwise be flagged up.
    - name: Gem patch methods
      pathStartsWith: lib/underware/patches

    - name: Configurator::Question asker methods
      pathStartsWith: lib/underware/configurator
      termStartsWith: ask_

    # Methods may be defined in namespaces and never used elsewhere in
    # Underware, as we just want them to be available when the namespace is
    # used as a binding when rendering templates.
    - name: Namespace methods
      pathStartsWith: lib/underware/namespaces
      allowedTerms:
      - local?

    # Things we want to explicitly not flag up as they may be useful in certain
    # situations in development even if they're not currently used in any
    # committed code.
    - name: Miscellaneous other terms
      allowedTerms:
      - UnderwareBench
      - debug!
      # Not currently used, but will be again as soon as we add back genders
      # file validation.
      - validate_genders_file

    # Things flagged up as unused which are actually used.
    - name: False positives
      allowedTerms:
      - body
      - run_command
      - each_value
      - storage
      - Certificate
